// Run manually (`node generate_ocr_assets.js`) whenever the vendored files in
// lib/ocr/ change - regenerates ocr-assets.js, which base64-embeds the OCR
// worker script, WASM core, and English trained data directly into the app
// so the single-file build has zero runtime fetches for any of it. See
// ocr.js for why this can't just be loaded from separate files at runtime:
// Chrome's fetch() refuses file:// URLs entirely, which is exactly how this
// app is normally opened (double-click, no server).
const fs = require("fs");
const path = require("path");

const DIR = path.join(__dirname, "lib", "ocr");
const toBase64 = (name) => fs.readFileSync(path.join(DIR, name)).toString("base64");

const out = `// Auto-generated by generate_ocr_assets.js - do not hand-edit.
// Base64-embedded OCR runtime: the (patched) tesseract-wasm worker script,
// its WebAssembly core, and the English trained-data model.
const OCR_WORKER_JS_BASE64 = "${toBase64("tesseract-worker.js")}";
const OCR_CORE_WASM_BASE64 = "${toBase64("tesseract-core-fallback.wasm")}";
const OCR_TRAINED_DATA_BASE64 = "${toBase64("eng_best_int.traineddata")}";
`;

const outPath = path.join(__dirname, "ocr-assets.js");
fs.writeFileSync(outPath, out);
console.log(`Wrote ${outPath} (${(out.length / 1024 / 1024).toFixed(1)} MB)`);
